services:
  mix_down_evt:
    build: ./mix_down_evt
    container_name: mix_down_evt
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/

  mix_down_llm:
    build: ./mix_down_llm
    container_name: mix_down_llm
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/
  ra_update_linhas_kml:
    build: ./ra_update_linhas_kml
    container_name: ra_update_linhas_kml
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/

  rmtc_crawler_node:
    build: ./rmtc_crawler_node
    container_name: rmtc_crawler_node
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/
