services:
  mix_down_evt:
    build: ./mix_down_evt
    container_name: mix_down_evt
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/

  mix_down_llm:
    build: ./mix_down_llm
    container_name: mix_down_llm
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/

  mix_down_motoristas:
    build: ./mix_down_motoristas
    container_name: mix_down_motoristas
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/
      
  mix_down_pecas:
    build: ./mix_down_pecas
    container_name: mix_down_pecas
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/

  mix_down_pos:
    build: ./mix_down_pos
    container_name: mix_down_pos
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/

  mix_down_rel_evt_trip:
    build: ./mix_down_rel_evt_trip
    container_name: mix_down_rel_evt_trip
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/

  mix_down_rel_pos_trip:
    build: ./mix_down_rel_pos_trip
    container_name: mix_down_rel_pos_trip
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/

  mix_down_tipos_eventos:
    build: ./mix_down_tipos_eventos
    container_name: mix_down_tipos_eventos
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/

  mix_down_trips:
    build: ./mix_down_trips
    container_name: mix_down_trips
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/

  mix_down_tst_combs:
    build: ./mix_down_tst_combs
    container_name: mix_down_tst_combs
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/

  mix_update_veiculos:
    build: ./mix_update_veiculos
    container_name: mix_update_veiculos
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/
     
  monitoramento_regra_os:
    build: ./monitoramento_regra_os
    container_name: monitoramento_regra_os
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/

  ra_update_linhas_kml:
    build: ./ra_update_linhas_kml
    container_name: ra_update_linhas_kml
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/

  rmtc_crawler_node:
    build: ./rmtc_crawler_node
    container_name: rmtc_crawler_node
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/home/grupo_fctufg/logs/
